version: '3.8'

services:

  web:
    image: footycr.azurecr.io/footy-tracker_web:latest
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    #volumes:
    #  - ./project:/usr/src/web
    ports:
      - 80:8000
    environment:
      - API_URL=http://api:8001
    depends_on:
      - api

  api:
    image: footycr.azurecr.io/footy-tracker_api:latest
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    #volumes:
    #  - ./project:/usr/src/api
   # ports:
   #   - 8004:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}