version: '3.8'

services:

  web:
    build: ./src/web
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    #volumes:
    #  - ./project:/usr/src/web
    ports:
      - 80:8000
    environment:
      - API_URL=http://api:8001
    depends_on:
      - api

  api:
    build: ./src/api
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    #volumes:
    #  - ./project:/usr/src/api
   # ports:
   #   - 8004:8000
    environment:
    - DATABASE_URL=postgresql://postgres:postgres@db:5432/footy
    depends_on:
      - db

  db:
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=footy
