version: '3.8'

services:

  api:
    build: .
    #command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:80
    environment:
    - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/footy
    - ML_MODEL_API_BASE_URL=http://127.0.0.1:8002/rating_based_predict
    - JWT_SECRET=mysecret
    depends_on:
      - db

  db:
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=footy