name: CI for FootyTracker API

on:
  pull_request:
    branches: 
      - main
    types: [opened, reopened, pushed, synchronize]
  push:
    branches:
      - main      
  workflow_dispatch:
    branches:     
      - main
      - feature/**

jobs:
  
  test-code:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r src/api/requirements-dev.txt

    - name: Run tests
      run: |
        cd src/api
        pytest tests
